package com.luccavergara.solaris.entity;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    LOGIN,
    LOGOUT,
    OPEN_CASH_REGISTER,
    CLOSE_CASH_REGISTER,
    REOPEN_CASH_REGISTER,
    CREATE_SALE,
    CREATE_SUPPLIER_ORDER,
    COMPLETE_SUPPLIER_ORDER,
    CANCEL_SUPPLIER_ORDER,
    UPDATE_SETTINGS,
    REGISTER_USER,
    CHANGE_PASSWORD,
    PASSWORD_RESET,
    EMAIL_VERIFIED
}